# Generated by Django 4.2.5 on 2023-09-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending_app', '0005_token_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='subscribed',
        ),
        migrations.AddField(
            model_name='token',
            name='subscribed_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
