# Generated by Django 4.2.5 on 2023-09-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending_app', '0006_remove_token_subscribed_token_subscribed_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='token',
            name='subscribed_id',
        ),
    ]
