# Generated by Django 4.2.5 on 2023-09-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending_app', '0007_chat_remove_token_subscribed_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=256)),
                ('chat_id', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
