# Generated by Django 4.2.5 on 2023-09-05 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sending_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
