# Generated by Django 4.2.5 on 2023-09-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='chat_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
