# Generated by Django 4.2.5 on 2023-09-05 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sending_app', '0008_telegramuser_delete_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='chat_id',
        ),
        migrations.AddField(
            model_name='token',
            name='telegram_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sending_app.telegramuser'),
        ),
    ]
