# Generated by Django 4.2.5 on 2023-09-05 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sending_app', '0009_remove_token_chat_id_token_telegram_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='telegram_user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sending_app.telegramuser'),
        ),
    ]
